///////////////////////////////////////////////////////////
//  ListSach.cs
//  Implementation of the Class ListSach
//  Generated by Enterprise Architect
//  Created on:      22-Sep-2026 3:49:47 PM
//  Original author: ADMIN
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ListSach {

	private int count;
	private List<Sach> list;



	~ListSach(){

	}

	public ListSach(){

	}

	/// 
	/// <param name="Sach"></param>
	public bool them(Sach Sach){

		return false;
	}

	/// 
	/// <param name="NXB"></param>
	public List<Sach> timSGKTheoNXB(string NXB){

		return null;
	}

	public double timThanhTienCaoNhat(){

		return 0;
	}

	public double tinhTongThanhTienSGK(){

		return 0;
	}

	public double tinhTongThanhTienSTK(){

		return 0;
	}

	public string toString(){

		return "";
	}

}//end ListSach