///////////////////////////////////////////////////////////
//  ListSach.cs
//  Implementation of the Class ListSach
//  Generated by Enterprise Architect
//  Created on:      22-Sep-2026 3:49:47 PM
//  Original author: ADMIN
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ListSach
{

    private int count; //biến count này thực chất là limit?
    public int Count
    {
        get { return count; }
        set { if (value >= 0) count = value; }
    }
    private List<Sach> list;

    public ListSach()
    {

    }
    public ListSach(int Count)
    {
        this.Count = Count;
        list = new List<Sach>(count);
    }
    /// 
    /// <param name="Sach"></param>
    public bool them(Sach SachMoi)
    {
        if(SachMoi == null)
        {
            return false;
        }
        foreach (Sach sach in list)
        {
            if (sach.Equals(SachMoi))
            {
                return false;
            }
        }
        list.Add(SachMoi);
        return true;
    }

    /// 
    /// <param name="NXB"></param>
    
    public List<Sach> timSGKTheoNXB(string NXB)
    {
        if (string.IsNullOrEmpty(NXB))
        {
            return null;
        }
        List<Sach> result = new List<Sach>();
        foreach (Sach sach in list)
        {
            if (sach is SachGiaoKhoa && sach.NhaXuatBan == NXB)
            {
                result.Add(sach);
            }
        }
        return result;
    }

    public double timThanhTienCaoNhat()
    {
        double max = 0;
        foreach (Sach sach in list)
        {
            double thanhTien = sach.getThanhTien();
            if (thanhTien > max)
            {
                max = thanhTien;
            }
        }
        return max;
    }

    public double tinhTongThanhTienSGK()
    {
        double tong = 0;
        foreach (Sach sach in list)
        {
            if (sach is SachGiaoKhoa)
                tong += sach.getThanhTien();
        }
        return tong;
    }

    public double tinhTongThanhTienSTK()
    {
        double tong = 0;
        foreach (Sach sach in list)
        {
            if (sach is SachThamKhao)
                tong += sach.getThanhTien();
        }
        return tong;
    }

    public string toString()
    {
        return "So luong sach hien co: "+count +
            "\nDanh sach cac sach: " + string.Join("\n===============================\n", list);
    }

}//end ListSach