///////////////////////////////////////////////////////////
//  Sach.cs
//  Implementation of the Class Sach
//  Generated by Enterprise Architect
//  Created on:      22-Sep-2026 3:48:50 PM
//  Original author: ADMIN
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public abstract class Sach {

	private double DonGia;
	private int MaSach;
	private int NgayNhap;
	private string NhaXuatBan;
	private int SoLuong;



	~Sach(){

	}

	public Sach(){

	}

	/// 
	/// <param name="MaSach"></param>
	/// <param name="NgayNhap"></param>
	/// <param name="DonGia"></param>
	/// <param name="SoLuong"></param>
	/// <param name="NhaXuatBan"></param>
	public Sach(string MaSach, DateTime NgayNhap, double DonGia, int SoLuong, string NhaXuatBan){

	}

	public double getDonGia(){

		return 0;
	}

	/// 
	/// <param name="DonGia"></param>
	public void getDonGia(double DonGia){

	}

	public string getMaSach(){

		return "";
	}

	/// 
	/// <param name="MaSach"></param>
	public void getMaSach(string MaSach){

	}

	public DateTime getNgayNhap(){

		return null;
	}

	/// 
	/// <param name="NgayNhap"></param>
	public void getNgayNhap(DateTime NgayNhap){

	}

	public string getNXB(){

		return "";
	}

	/// 
	/// <param name="NhaXuatban"></param>
	public void getNXB(string NhaXuatban){

	}

	public int getSoLuong(){

		return 0;
	}

	/// 
	/// <param name="SoLuong"></param>
	public void getSoLuong(int SoLuong){

	}

	public double getThanhTien(){

		return 0;
	}

	public string ToString(){

		return "";
	}

}//end Sach