///////////////////////////////////////////////////////////
//  SachGiaoKhoa.cs
//  Implementation of the Class SachGiaoKhoa
//  Generated by Enterprise Architect
//  Created on:      22-Sep-2026 3:49:15 PM
//  Original author: ADMIN
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


public enum Tinhtrang
{
    Moi,
    Cu,
}
public class SachGiaoKhoa : Sach
{

    private Tinhtrang tinhtrang;
    
    public Tinhtrang TinhTrang
    {
        get { return tinhtrang; }
        set { tinhtrang = value; }
    }
    /// 
    /// <param name="MaSach"></param>
    /// <param name="NgayNhap"></param>
    /// <param name="DonGia"></param>
    /// <param name="SoLuong"></param>
    /// <param name="NhaXuatBan"></param>
    /// <param name="TinhTrang"></param>
    public SachGiaoKhoa(string MaSach, DateTime NgayNhap, double DonGia, int SoLuong, string NhaXuatBan, Tinhtrang TinhTrang)
        : base(MaSach, NgayNhap, DonGia, SoLuong, NhaXuatBan)
    {
        this.TinhTrang = TinhTrang;
    }

    public SachGiaoKhoa()
    {

    }

    /// <summary>
    /// override
    /// </summary>
    public override double getThanhTien()
    {

        return DonGia*SoLuong;
    }

    /// 
    /// <param name="TinhTrang"></param>
    public void setTinhTrang(Tinhtrang TinhTrang)
    {
        this.TinhTrang = TinhTrang;
    }

    public Tinhtrang getTinhTrang()
    {

        return TinhTrang;
    }

    /// <summary>
    /// override
    /// </summary>
    
    public override string ToString()
        
    {
        return base.ToString() + "\nTinh trang: "+TinhTrang;
    }

}//end SachGiaoKhoa