///////////////////////////////////////////////////////////
//  SachThamKhao.cs
//  Implementation of the Class SachThamKhao
//  Generated by Enterprise Architect
//  Created on:      22-Sep-2026 3:49:34 PM
//  Original author: ADMIN
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class SachThamKhao :Sach
{

    private double thue;

    public double Thue
    {
        get { return thue; }
        set { if (value >= 0) thue = value; }
    }
    /// 
    /// <param name="MaSach"></param>
    /// <param name="NgayNhap"></param>
    /// <param name="DonGia"></param>
    /// <param name="SoLuong"></param>
    /// <param name="NhaXuatBan"></param>
    /// <param name="Thue"></param>
    public SachThamKhao(string MaSach, DateTime NgayNhap, double DonGia, int SoLuong, string NhaXuatBan, double Thue)
        :base(MaSach, NgayNhap, DonGia, SoLuong, NhaXuatBan)
    {
        this.Thue = Thue;
    }

    public SachThamKhao()
    {

    }

    public double getThue()
    {

        return Thue;
    }

    /// 
    /// <param name="Thue"></param>
    public void setThue(double Thue)
    {
        this.Thue = Thue;
    }

    public override double getThanhTien()
    {
        return DonGia*SoLuong*Thue;
    }
    public override string ToString()
    {
        return base.ToString() + "\nThue: " + Thue;
    }

}//end SachThamKhao