///////////////////////////////////////////////////////////
//  SachGiaoKhoa.cs
//  Implementation of the Class SachGiaoKhoa
//  Generated by Enterprise Architect
//  Created on:      22-Sep-2026 3:49:15 PM
//  Original author: ADMIN
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class SachGiaoKhoa : Sach {

	private bool TinhTrang;



	~SachGiaoKhoa(){

	}

	/// 
	/// <param name="MaSach"></param>
	/// <param name="NgayNhap"></param>
	/// <param name="DonGia"></param>
	/// <param name="SoLuong"></param>
	/// <param name="NhaXuatBan"></param>
	/// <param name="TinhTrang"></param>
	public SachGiaoKhoa(string MaSach, DateTime NgayNhap, double DonGia, int SoLuong, string NhaXuatBan, bool TinhTrang){

	}

	public SachGiaoKhoa(){

	}

	/// <summary>
	/// override
	/// </summary>
	public double getThanhTien(){

		return 0;
	}

	/// 
	/// <param name="TinhTrang"></param>
	public void getTinhTrang(bool TinhTrang){

	}

	public bool getTinhTrang(){

		return false;
	}

	/// <summary>
	/// override
	/// </summary>
	public string toString(){

		return "";
	}

	public override string ToString(){

		return "";
	}

}//end SachGiaoKhoa