///////////////////////////////////////////////////////////
//  Sach.cs
//  Implementation of the Class Sach
//  Generated by Enterprise Architect
//  Created on:      22-Sep-2026 3:57:37 PM
//  Original author: ADMIN
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public abstract class Sach
{

    private double dongia;
    public double DonGia
    {
        get { return dongia; }
        set { if (value > 0) dongia = value; }
    }
    private string masach;
    public string MaSach
    {
        get { return masach; }
        set { if (!string.IsNullOrEmpty(value)) masach = value; }
    }

    private DateTime ngaynhap;
    public DateTime NgayNhap
    {
        get { return ngaynhap; }
        set { if (value <= DateTime.Now) ngaynhap = value; }
    }

    private string nhaxuatban;
    public string NhaXuatBan
    {
        get { return nhaxuatban; }
        set { if (!string.IsNullOrEmpty(value)) nhaxuatban = value; }
    }

    private int soluong;
    public int SoLuong
    {
        get { return soluong; }
        set { if (value > 0) soluong = value; }
    }

    public Sach()
    {

    }

    /// 
    /// <param name="MaSach"></param>
    /// <param name="NgayNhap"></param>
    /// <param name="DonGia"></param>
    /// <param name="SoLuong"></param>
    /// <param name="NhaXuatBan"></param>
    public Sach(string MaSach, DateTime NgayNhap, double DonGia, int SoLuong, string NhaXuatBan)
    {
        this.MaSach = MaSach;
        this.NgayNhap = NgayNhap;
        this.DonGia = DonGia;
        this.SoLuong = SoLuong;
        this.NhaXuatBan = NhaXuatBan;
    }

    public double getDonGia()
    {
        return DonGia;
    }

    /// 
    /// <param name="DonGia"></param>
    public void setDonGia(double DonGia)
    {
        this.DonGia = DonGia;
    }

    public string getMaSach()
    {

        return MaSach;
    }

    /// 
    /// <param name="MaSach"></param>
    public void setMaSach(string MaSach)
    {
        this.MaSach = MaSach;
    }

    public DateTime getNgayNhap()
    {

        return NgayNhap;
    }

    /// 
    /// <param name="NgayNhap"></param>
    public void setNgayNhap(DateTime NgayNhap)
    {
        this.NgayNhap = NgayNhap;
    }

    public string getNXB()
    {

        return NhaXuatBan;
    }

    /// 
    /// <param name="NhaXuatban"></param>
    public void setNXB(string NhaXuatban)
    {
        this.NhaXuatBan = NhaXuatban;
    }

    public int getSoLuong()
    {

        return SoLuong;
    }

    /// 
    /// <param name="SoLuong"></param>
    public void setSoLuong(int SoLuong)
    {
        this.SoLuong = SoLuong;
    }

    public virtual double getThanhTien()
    {

        return dongia * soluong;
    }

    public virtual string ToString()
    {
        return "Ma sach: " + MaSach +
            "\nNgay nhap: " + NgayNhap.ToString("dd/MM/yyyy") +
            "\nDon gia: " + DonGia +
            "\nSo luong: " + SoLuong +
            "\nNha xuat ban: " + NhaXuatBan;
    }


    //hàm Equals và GetHashCode() ?? so sánh các ??i t??ng Sach d?a trên mã sách (MaSach)
    public override bool Equals(object obj)
    {
        if(obj == null) return false;
        if(obj.GetType() != GetType()) return false;
        if (obj is Sach otherSach)
        {
            return this.MaSach == otherSach.MaSach;
        }
        return false;
    }
    public override int GetHashCode()
    {
        return MaSach.GetHashCode();
    }
}//end Sach