///////////////////////////////////////////////////////////
//  Sach.cs
//  Implementation of the Class Sach
//  Generated by Enterprise Architect
//  Created on:      17-Sep-2026 4:49:08 PM
//  Original author: ADMIN
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public abstract class Sach {

	private double DonGia;
	private int MaSach;
	private int NgayNhap;
	private string NhaXuatBan;
	private int SoLuong;

	public Sach(){

	}

	~Sach(){

	}

	public double ThanhTien(){

		return 0;
	}

}//end Sach