///////////////////////////////////////////////////////////
//  SachThamKhao.cs
//  Implementation of the Class SachThamKhao
//  Generated by Enterprise Architect
//  Created on:      22-Sep-2026 3:49:34 PM
//  Original author: ADMIN
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class SachThamKhao : Sach {

	private double Thue;



	~SachThamKhao(){

	}

	/// 
	/// <param name="MaSach"></param>
	/// <param name="NgayNhap"></param>
	/// <param name="DonGia"></param>
	/// <param name="SoLuong"></param>
	/// <param name="NhaXuatBan"></param>
	/// <param name="Thue"></param>
	public SachThamKhao(string MaSach, DateTime NgayNhap, double DonGia, int SoLuong, string NhaXuatBan, double Thue){

	}

	public SachThamKhao(){

	}

	public double getThue(){

		return 0;
	}

	/// 
	/// <param name="Thue"></param>
	public void getThue(double Thue){

	}

	public double ThanhTien(){

		return 0;
	}

}//end SachThamKhao