///////////////////////////////////////////////////////////
//  SachGiaoKhoa.cs
//  Implementation of the Class SachGiaoKhoa
//  Generated by Enterprise Architect
//  Created on:      17-Sep-2026 4:49:08 PM
//  Original author: ADMIN
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class SachGiaoKhoa : Sach {

	private string TinhTrang;

	public SachGiaoKhoa(){

	}

	~SachGiaoKhoa(){

	}

	public double ThanhTien(){

		return 0;
	}

}//end SachGiaoKhoa