///////////////////////////////////////////////////////////
//  SachThamKhao.cs
//  Implementation of the Class SachThamKhao
//  Generated by Enterprise Architect
//  Created on:      17-Sep-2026 4:49:08 PM
//  Original author: ADMIN
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class SachThamKhao : Sach {

	private double Thue;

	public SachThamKhao(){

	}

	~SachThamKhao(){

	}

	public double ThanhTien(){

		return 0;
	}

}//end SachThamKhao