///////////////////////////////////////////////////////////
//  GiaoDich.cs
//  Implementation of the Class GiaoDich
//  Generated by Enterprise Architect
//  Created on:      20-Sep-2026 2:12:29 PM
//  Original author: ADMIN
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public abstract class GiaoDich
{

    public double dongia { get; }
    public string magd { get; }
    public int ngaygd { get; }
    private int soluong;

    public int SoLuong
    {
        get { return soluong; }
        set { if (value > 0) soluong = value; }
    }

    public GiaoDich(string magd, int ngaygd, double dongia, int soluong)
    {
        this.magd = magd;
        this.ngaygd = ngaygd;
        this.dongia = dongia;
        this.soluong = soluong;
    }


    public virtual decimal ThanhTien()
    {
        return (decimal)(dongia * soluong);
    }
    public static void ToString(GiaoDich gd)
    {
        Console.WriteLine("Ma GD: " + gd.magd);
        Console.WriteLine("Ngay GD: " + gd.ngaygd);
        Console.WriteLine("Don Gia: " + gd.dongia);
        Console.WriteLine("So Luong: " + gd.soluong);
        Console.WriteLine("Thanh Tien: " + gd.ThanhTien());
    }
}//end GiaoDich