///////////////////////////////////////////////////////////
//  GiaoDichTienTe.cs
//  Implementation of the Class GiaoDichTienTe
//  Generated by Enterprise Architect
//  Created on:      20-Sep-2026 2:12:36 PM
//  Original author: ADMIN
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class GiaoDichTienTe : GiaoDich
{

    private LoaiTien loaitien;
    private double tigia;

    public GiaoDichTienTe(string a, int b, double c, int d, double tigia, LoaiTien loaitien) : base(a, b, c, d)
    {
        this.tigia = tigia;
        this.loaitien = loaitien;
    }


    public override decimal ThanhTien()
    {
        if (loaitien == LoaiTien.TienViet)
        {
            return (decimal)(dongia * SoLuong);
        }
        else
            return (decimal)(dongia * SoLuong * tigia);
    }

}//end GiaoDichTienTe