///////////////////////////////////////////////////////////
//  GiaoDichVang.cs
//  Implementation of the Class GiaoDichVang
//  Generated by Enterprise Architect
//  Created on:      20-Sep-2026 2:12:33 PM
//  Original author: ADMIN
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class GiaoDichVang : GiaoDich
{

    private string loaivang;

    public GiaoDichVang(string a, int b, double c, int d, string loaivang) : base(a, b, c, d)
    {
        this.loaivang = loaivang;
    }

    public override decimal ThanhTien()
    {
        return (decimal)(dongia * SoLuong);
    }

}//end GiaoDichVang