///////////////////////////////////////////////////////////
//  LoaiTien.cs
//  Implementation of the Enumeration LoaiTien
//  Generated by Enterprise Architect
//  Created on:      20-Sep-2026 2:12:40 PM
//  Original author: ADMIN
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public enum LoaiTien : int 
{

	TienViet,
	TienUSD,
	TienEuro,
	
}//end LoaiTien