///////////////////////////////////////////////////////////
//  ChuyenXe.cs
//  Implementation of the Class ChuyenXe
//  Generated by Enterprise Architect
//  Created on:      17-Sep-2026 3:36:31 PM
//  Original author: ADMIN
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public abstract class ChuyenXe
{

    public double DoanhThu { get; }
    private string HoTenTaiXe;
    private string MaSoChuyen;
    private string SoXe;

    public ChuyenXe(double DoanhThu, string HoTenTaiXe, string MaSoChuyen, string SoXe)
    {
        this.DoanhThu = DoanhThu;
        this.HoTenTaiXe = HoTenTaiXe;
        this.MaSoChuyen = MaSoChuyen;
        this.SoXe = SoXe;
    }

    ~ChuyenXe()
    {

    }

    

}//end ChuyenXe