///////////////////////////////////////////////////////////
//  ChuyenXeNgoaiThanh.cs
//  Implementation of the Class ChuyenXeNgoaiThanh
//  Generated by Enterprise Architect
//  Created on:      17-Sep-2026 3:37:26 PM
//  Original author: ADMIN
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ChuyenXeNgoaiThanh : ChuyenXe
{

    private string NoiDen;
    private int SoNgay;

    public ChuyenXeNgoaiThanh(double a, string b, string c, string d, string Noiden, int SoNgay) : base(a, b, c, d)
    {
        this.NoiDen = Noiden;
        this.SoNgay = SoNgay;
    }


    ~ChuyenXeNgoaiThanh()
    {

    }

}//end ChuyenXeNgoaiThanh