///////////////////////////////////////////////////////////
//  ChuyenXeNoiThanh.cs
//  Implementation of the Class ChuyenXeNoiThanh
//  Generated by Enterprise Architect
//  Created on:      17-Sep-2026 3:37:07 PM
//  Original author: ADMIN
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ChuyenXeNoiThanh : ChuyenXe
{

    private double SoKmDiDuoc;
    private int SoTuyen;

    public ChuyenXeNoiThanh(double a, string b, string c, string d, double SoKmDiDuoc, int SoTuyen) : base(a, b, c, d)
    {
        this.SoKmDiDuoc = SoKmDiDuoc;
        this.SoTuyen = SoTuyen;
    }

    ~ChuyenXeNoiThanh()
    {

    }

}//end ChuyenXeNoiThanh